title:            JeskTop
description:      A jekyll theme. Because I scribble.
url:              http://jesktop.com/
domain_name:      jesktop.com
signoff:          JeskTop
disqus_shortname: jesktopcom
facebook_appid:   1175282290
google_analytics: UA-47292018-1
links: 
  - name:         关于
    url:          /about
  - name:         微博
    url:          http://weibo.com/jesktop
  - name:         Email
    url:          mailto:frayay@gmail.com
  - name:         GitHub
    url:          http://github.com/jesktop
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
